In [28]:
import numpy as np

## Create Numpy Array

```python
np.array([1,2,3,4])
np.array([(1,2,3,4,5),(2,3,4,5,6)])
```
> insert a list or lists

```python
np.zeros([1,3])
```
> fill array with zero

```python
np.ones([1,2,3])
```
> fill array with one

```python
np.empty((2,2))
```
```python
np.arrange(10,50,5)
```
> like range function in python
```python
np.linespace(0,1,10)
```
> return from 0 to 1 generate 10 numbers 

In [9]:
np1 = np.array([1,2,3,4])
np1

array([1, 2, 3, 4])

In [12]:
np2 = np1+1
np2

array([2, 3, 4, 5])

In [13]:
np1+np2

array([3, 5, 7, 9])

In [30]:
np.array([(1,2,3,4,5),(2,3,4,5,6)])

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [38]:
np.empty((2,2))

array([[9.39198689e-312, 0.00000000e+000],
       [9.34562258e-307, 3.62651150e-317]])

In [43]:
np.arange(10,50,4)

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [39]:
np.linspace(1,9,20)

array([1.        , 1.42105263, 1.84210526, 2.26315789, 2.68421053,
       3.10526316, 3.52631579, 3.94736842, 4.36842105, 4.78947368,
       5.21052632, 5.63157895, 6.05263158, 6.47368421, 6.89473684,
       7.31578947, 7.73684211, 8.15789474, 8.57894737, 9.        ])

## Show Information

### dimension

```python
nparray.ndim
```
> return array dimension
### matrix shape
```python
nparray.shape
```
> return array size
### data type
```python
nparray.dtype
```
> return array data type

In [14]:
#dimension
np1.ndim

1

In [15]:
#rows X columns 
np1.shape

(4,)

In [16]:
#datatype
np1.dtype

dtype('int32')

In [21]:
#generate data from scv file
np3 = np.genfromtxt('data.csv')
np3

array(nan)

## Change array

### Change size
```python
np.reshape
```
> Returns an array containing the same data with a new shape.

### Change datadype
```python
np.astype
```
> Copy of the array, cast to a specified type.

In [23]:
np1.reshape([4,1])

array([[1],
       [2],
       [3],
       [4]])

In [24]:
np1.reshape([2,2])

array([[1, 2],
       [3, 4]])

In [27]:
np1.astype(np.int16)

array([1, 2, 3, 4], dtype=int16)

## Select data

In [ ]:
np.fromfunction